#ansible-playbook /mnt/f/zia-net-automation/EVPN_VxLAN/1_Inter_VRFs_route_leak/route_leaking_between_DevWeb_andSharedServ_playbook.yaml -i /mnt/f/zia-net-automation/EVPN_VxLAN/1_Inter_VRFs_route_leak/host.yaml
- name: ROUTE Leaking for DevWeb & SharedServ
  hosts: border_leaves
  gather_facts: no
  tasks:
  - name: route leaking for DevWeb & SharedServ
    arista.eos.eos_config:
      src: route_leaking_between_DevWeb_andSharedServ.j2
      save_when : changed