#ansible-playbook /mnt/f/zia-net-automation/EVPN_VxLAN/1_Inter_VRFs_route_leak/vlan255_vrfSHARED_config_playbook.yaml -i /mnt/f/zia-net-automation/EVPN_VxLAN/1_Inter_VRFs_route_leak/host.yaml
- name: VLAN255 and SHARED VRF creation
  hosts: leaves
  gather_facts: no
  tasks:
  - name: vlan255 and vrf SHARED creation and save
    arista.eos.eos_config:
      src: vlan255_vrfSHARED_config.j2
      save_when : changed
