#ansible-playbook /mnt/f/zia-net-automation/EVPN_VxLAN/ansible_connectivity_check/connectivity_check_palybook.yaml -i /mnt/f/zia-net-automation/EVPN_VxLAN/ansible_connectivity_check/host.yaml
- name: Leaves switches MLAG Config 
  hosts: MLAG_leaves
  gather_facts: no
  tasks:
  - name: MLAG configuration
    arista.eos.eos_config:
      src: mlag_base_template.j2
- name: Leaves Base Config 
  hosts: leaves
  gather_facts: no
  tasks:
  - name: configuring base config of leaf switches
    arista.eos.eos_config:
      src: leaves_base_template.j2